version: '3.4'

services:
  db:
    container_name: db
    image: mysql:5.7
    networks:
      backend:
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=data
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=app_user
    volumes:
      - "mysqlvol:/var/lib/mysql"
    ports:
      - "3366:3306"

  redis_db:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
        ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - /tmp:/bitnami/redis/data
    networks:
     - backend

  php:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis_db
      - db
    networks:
      - backend

  web:
    image: nginx:latest
    ports:
      - '8888:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - backend

networks:
  backend:

volumes:
  mysqlvol:
